### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toggleSelectionOption' of undefined

### ISSUE THREAD

**Issue by akyag** [Kraoz/atom-auto-replace-in-selection#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Fedora release
**Thrown From**: [auto-replace-in-selection](https://github.com/Kraoz/atom-auto-replace-in-selection) package, v4.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'toggleSelectionOption' of undefined

```
At /home/akya/.atom/packages/auto-replace-in-selection/lib/auto-replace-in-selection.coffee:21

TypeError: Cannot read property 'toggleSelectionOption' of undefined
    at Function.module.exports.AutoReplaceInSelection.find_and_replace_shown (/home/akya/.atom/packages/auto-replace-in-selection/lib/auto-replace-in-selection.coffee:21:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib64/atom/src/command-registry.js:260:29)
    at /usr/lib64/atom/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib64/atom/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib64/atom/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib64/atom/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/lib64/atom/src/window-event-handler.js:3:61)
```
### Commands

```
     -6:14.9.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active.mini)
     -6:13.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:13.1.0 autoclose-html:close-and-complete (atom-text-editor.editor.is-focused)
  2x -6:12.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -6:11.1.0 core:save (atom-text-editor.editor.is-focused)
     -5:43.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused.mini)
     -5:43.3.0 snippets:expand (atom-text-editor.editor.is-focused.mini)
     -5:43.2.0 editor:indent (atom-text-editor.editor.is-focused.mini)
     -5:42.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused.mini)
     -5:42.9.0 snippets:expand (atom-text-editor.editor.is-focused.mini)
     -5:42.9.0 editor:indent (atom-text-editor.editor.is-focused.mini)
     -5:19.7.0 core:delete (atom-text-editor.editor.is-focused.mini)
     -5:03.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:51.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:45.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:55.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "wrap-guide"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "native-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.9
atom-lorempixel, v0.1.0
auto-replace-in-selection, v4.0.0
autoclose-html, v0.23.0
color-picker, v2.2.2
compare-files, v0.6.2
file-icons, v1.7.17
htmlhint, v1.1.4
linter, v1.11.14
minimap, v4.24.7
native-ui, v0.18.3
pigments, v0.31.2
project-manager, v2.9.7
tidy-tabs, v0.3.0

# Dev
No dev packages
```

**Comment by vr8hub** [comment]
I got this same error in Mac Atom 1.9.9, auto-replace-in-selection package, v4.0.0, when just hitting Ctrl-F on the Settings/Packages page.

**Comment by hgoodman** [comment]
This bug is still present. All I did was install the package, switch to an editor and press <kbd>&#8984;</kbd>+<kbd>F</kbd>.

**Comment by sijpkes** [comment]
Met too.  Getting this just while doing day to day work. This time command - F on css file.

**Comment by C-PrekshaShah** [comment]
I get this error time to time. Rebooting computer and/or atom helps.
