### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null

### ISSUE THREAD

**Issue by vr8hub** [Kraoz/atom-auto-replace-in-selection#3]
[Enter steps to reproduce below:]
1. Start Atom.
2. Open Settings.
3. Click Packages tab.
4. Type Ctrl-F to find. The cursor is correctly positioned in the "Find in Current Buffer" at the bottom of the page, but it throws this error.

**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6
**Thrown From**: [auto-replace-in-selection](https://github.com/Kraoz/atom-auto-replace-in-selection) package, v4.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null

```
At /Users/vrice/.atom/packages/auto-replace-in-selection/lib/auto-replace-in-selection.coffee:15

TypeError: Cannot read property 'getSelectedBufferRange' of null
    at Function.module.exports.AutoReplaceInSelection.has_selection (/Users/vrice/.atom/packages/auto-replace-in-selection/lib/auto-replace-in-selection.coffee:15:38)
    at Function.module.exports.AutoReplaceInSelection.find_and_replace_shown (/Users/vrice/.atom/packages/auto-replace-in-selection/lib/auto-replace-in-selection.coffee:21:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:58.3.0 find-and-replace:show (atom-text-editor.editor.mini.is-focused)
  3x -0:01.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.0 find-and-replace:show (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10 (inactive)
auto-replace-in-selection, v4.0.0 (active)
color-picker, v2.2.2 (active)
file-icons, v1.7.18 (active)
file-types, v0.5.4-p1 (active)
minimap, v4.24.7 (active)
minimap-find-and-replace, v4.5.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (active)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (active)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by drawcard** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [auto-replace-in-selection](https://github.com/Kraoz/atom-auto-replace-in-selection) package 4.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null

```
At /Users/drawcard/.atom/packages/auto-replace-in-selection/lib/auto-replace-in-selection.coffee:15

TypeError: Cannot read property 'getSelectedBufferRange' of null
    at Function.module.exports.AutoReplaceInSelection.has_selection (/packages/auto-replace-in-selection/lib/auto-replace-in-selection.coffee:15:38)
    at Function.module.exports.AutoReplaceInSelection.find_and_replace_shown (/packages/auto-replace-in-selection/lib/auto-replace-in-selection.coffee:21:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -9:46.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -6:51.3.0 project-find:show (div.tool-panel.tree-view)
     -6:49.9.0 core:confirm (input.hidden-input)
  3x -6:16.7.0 core:backspace (input.hidden-input)
     -6:14.9.0 core:confirm (input.hidden-input)
     -0:15 find-and-replace:show (atom-pane.pane)
```

### Non-Core Packages

```
aligner-php 1.1.1 
atom-beautify 0.30.3 
atom-wordpress 0.3.0 
auto-replace-in-selection 4.0.0 
autocomplete-bibtex 0.7.0 
autocomplete-paths 1.0.5 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
code-peek 1.4.20 
color-picker 2.2.5 
duplicate-line-or-selection 0.9.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.8 
fonts 3.0.2 
git-time-machine 1.5.9 
html-to-css 0.2.2 
imdone-atom 2.2.6 
intentions 1.1.2 
less-autocompile 1.0.0 
line-diff-details 1.8.0 
linter 2.2.0 
linter-bootlint 1.0.4 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-jshint 3.1.4 
linter-jsonlint 1.3.0 
linter-just-say-no 0.7.3 
linter-less 2.6.0 
linter-liferay 3.0.0 
linter-markdownlint 1.0.1 
linter-php 1.3.2 
linter-processing 2.2.2 
linter-proselint 3.2.1 
linter-python 3.1.2 
linter-ruby 1.2.5 
linter-shellcheck 1.4.4 
linter-stylelint 3.10.0 
linter-ui-default 1.6.2 
linter-vagrant-validate 1.1.0 
linter-write-good 0.9.0 
linter-xmllint 1.4.3 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
php-debug 0.2.4 
pigments 0.39.1 
project-manager 3.3.5 
sass-autocompile 0.13.3 
sort-lines 0.14.0 
sorter 1.1.0 
sync-settings 0.8.2 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
wordpress-suite 1.0.4 
wp-snippets 0.2.10 
```

**Comment by gingerbeardman** [comment]
+1
